### PR TITLE
Properly support both CJS and ESM

### LINKED ISSUE #20: Cannot find module ./MessageBuilder
It runs on windows perfectly fine but using ubuntu rn. 

Error: Cannot find module './MessageBuilder'
Require stack:
- /root/Snooful-master/node_modules/discord-webhook-node/src/classes/webhook.js
- /root/Snooful-master/node_modules/discord-webhook-node/src/index.js
- /root/Snooful-master/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/Snooful-master/node_modules/discord-webhook-nod                                                                                                                                                             e/src/classes/webhook.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/Snooful-master/node_modules/discord-webhook-nod                                                                                                                                                             e/src/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/Snooful-master/src/index.js:40:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js                                                                                                                                                             :71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Snooful-master/node_modules/discord-webhook-node/src/classes/webhook.                                                                                                                                                             js',
    '/root/Snooful-master/node_modules/discord-webhook-node/src/index.js',
    '/root/Snooful-master/src/index.js'

### PR DESCRIPTION
**Pull request by CarbonAlabel**
Resolves #20

### CODE REVIEW

**Comment by C0kkie** [comment]
I hope this solves my Problem too, cuz with the newst version i stil get

SyntaxError: The requested module 'discord-webhook-node' does not provide an export named 'Webhook'

**Comment by C0kkie** [comment]
My Code

import { Webhook, MessageBuilder } from 'discord-webhook-node';

`try {
            let hook = Webhook("TESTURL");
            let embed = MessageBuilder()
                .setTitle("Test")
                .setTimestamp();

            textObjects.forEach(elem => {
                embed.addField(elem.fieldTitle, elem.fieldValue)
            });`
} catch(e) {
            console.log(e)
        }

**Comment by C0kkie** [comment]
hm i still get the error i posted after the update, any idea?

**Comment by C0kkie** [comment]
@matthew1232

**Comment by C0kkie** [comment]
Alright, nvm. I need to use 

import Webhook from 'discord-webhook-node';
import MessageBuilder from 'discord-webhook-node';

**Comment by matthew1232** [comment]
Do both webhook and messagebuilder perform as expected though?

**Comment by C0kkie** [comment]
Code

import Webhook from 'discord-webhook-node';
import MessageBuilder from 'discord-webhook-node';

let hook = new Webhook(url);
let embed = new MessageBuilder()
                  .setTitle(title)
                .setTimestamp();
hook.send(embed);

results in a "TypeError: Webhook is not a constructor"

if i use 

let hook = Webhook(url);
let embed = MessageBuilder()

Then i get "is not a function"

@matthew1232

**Comment by CarbonAlabel** [comment]
@C0kkie I've been trying to reproduce the errors you've reported here and those in #16 but been unable to. Could you respond with more details, such as the version of Node you're running, and the versions of any other tools you're using?

**Comment by C0kkie** [comment]
I use node version 14

**Comment by C0kkie** [comment]
I try to use it within a gtav framework called Alt:V https://altv.mp/#/
We have many other packages installed like mysql2 where it works like a charm

**Comment by C0kkie** [comment]
the only thing whats written there that they are using ES6

**Comment by CarbonAlabel** [comment]
@C0kkie I've taken a quick look at Alt:V, and it appears to be using Node v12.4.0 internally, which is over a year old. Back then, ESM support in Node was still in early experimental stages, and as such, it doesn't support the `exports` field that's being used here to support both systems. Trying to import the package with Node v12.4.0 does indeed produce the exact errors you have reported.

Assuming you can't get the devs of Alt:V to upgrade to a newer version of Node, and ignoring solutions such as making a separate version of this package which only supports ESM, I would suggest you just use the default import and manually destructure it:
```js
import discord_webhook_node from "discord-webhook-node";
const { Webhook, MessageBuilder } = discord_webhook_node;
```

**Comment by C0kkie** [comment]
Alright thanks. 

import discord_webhook_node from "discord-webhook-node";
const { Webhook, MessageBuilder } = discord_webhook_node;

Solved my problem

**Pull request merged**
